### ISSUE TITLE
Unable to withdraw rewards. "Illegal Value in TxOut"

### ISSUE THREAD

**Issue by vshybalov** [input-output-hk/cardano-cli#965]
## Description

I am unable to create transaction with cardano-cli 9.4.1.0, 10.1.1.0 to withdraw rewards. The last working version was cardano-cli 9.2.1.0.

## Steps to Reproduce

The amount in variable below is 2276043199 without any negative symbols. 

```
cardano-cli conway transaction build --mainnet --witness-override 2 --tx-in ${TXIN} --withdrawal "${STAKE_ADDRESS}+${REWARDS_AMOUNT}" --tx-out "${DSTADDRESS}+${REWARDS_AMOUNT}" --change-address ${ADDRESS} --out-file tx.raw

cardano-cli: Illegal Value in TxOut: MaryValue (Coin (-1272733348)) (MultiAsset (fromList []))
CallStack (from HasCallStack):
  error, called at src/Cardano/Ledger/Babbage/TxOut.hs:401:25 in cardano-ledger-babbage-1.9.0.0-Ek1rsoJwqvmCy8NgTgKsxr:Cardano.Ledger.Babbage.TxOut
  mkTxOut, called at src/Cardano/Ledger/Babbage/TxOut.hs:372:44 in cardano-ledger-babbage-1.9.0.0-Ek1rsoJwqvmCy8NgTgKsxr:Cardano.Ledger.Babbage.TxOut
  BabbageTxOut, called at src/Cardano/Ledger/Conway/TxOut.hs:40:26 in cardano-ledger-conway-1.16.2.0-4XQSafjZx8OK5CVEBZ7pWD:Cardano.Ledger.Conway.TxOut
  mkBasicTxOut, called at internal/Cardano/Api/Tx/Body.hs:3084:13 in cardano-api-9.3.0.0-C0QPA7dowbsCao5S5QVkzf-internal:Cardano.Api.Tx.Body
  toShelleyTxOutAny, called at internal/Cardano/Api/Tx/Body.hs:2339:41 in cardano-api-9.3.0.0-C0QPA7dowbsCao5S5QVkzf-internal:Cardano.Api.Tx.Body
```

## Additional Context

There were no issues, before the new versions of cli, in terms of rewards claiming, nothing changed on our end.

## Possible Solution

-

**Comment by kieth314M7** [comment]
> ## Description
> I am unable to create transaction with cardano-cli 9.4.1.0, 10.1.1.0 to withdraw rewards. The last working version was cardano-cli 9.2.1.0.
> 
> ## Steps to Reproduce
> The amount in variable below is 2276043199 without any negative symbols.
> 
> ```
> cardano-cli conway transaction build --mainnet --witness-override 2 --tx-in ${TXIN} --withdrawal "${STAKE_ADDRESS}+${REWARDS_AMOUNT}" --tx-out "${DSTADDRESS}+${REWARDS_AMOUNT}" --change-address ${ADDRESS} --out-file tx.raw
> 
> cardano-cli: Illegal Value in TxOut: MaryValue (Coin (-1272733348)) (MultiAsset (fromList []))
> CallStack (from HasCallStack):
>   error, called at src/Cardano/Ledger/Babbage/TxOut.hs:401:25 in cardano-ledger-babbage-1.9.0.0-Ek1rsoJwqvmCy8NgTgKsxr:Cardano.Ledger.Babbage.TxOut
>   mkTxOut, called at src/Cardano/Ledger/Babbage/TxOut.hs:372:44 in cardano-ledger-babbage-1.9.0.0-Ek1rsoJwqvmCy8NgTgKsxr:Cardano.Ledger.Babbage.TxOut
>   BabbageTxOut, called at src/Cardano/Ledger/Conway/TxOut.hs:40:26 in cardano-ledger-conway-1.16.2.0-4XQSafjZx8OK5CVEBZ7pWD:Cardano.Ledger.Conway.TxOut
>   mkBasicTxOut, called at internal/Cardano/Api/Tx/Body.hs:3084:13 in cardano-api-9.3.0.0-C0QPA7dowbsCao5S5QVkzf-internal:Cardano.Api.Tx.Body
>   toShelleyTxOutAny, called at internal/Cardano/Api/Tx/Body.hs:2339:41 in cardano-api-9.3.0.0-C0QPA7dowbsCao5S5QVkzf-internal:Cardano.Api.Tx.Body
> ```
> 
> ## Additional Context
> There were no issues, before the new versions of cli, in terms of rewards claiming, nothing changed on our end.
> 
> ## Possible Solution

@vshybalov Thanks for posting the issue.

Your query would be best dealt with by the support team.

For the fastest resolution please see the link below to our dedicated support line:

Support : [Cardano Help Center](https://cardano-zendesk.web.app/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by carbolymer** [comment]
It's not quite obvious where did the value `(Coin (-1272733348))` come from. Could you provide full reproduction command with concrete values and addresses instead of shell variables?

**Comment by vshybalov** [comment]
Hello @carbolymer 

Please see below the latest attempt with all the values unhidden.

```
cardano-cli version 
cardano-cli 10.1.1.0 - linux-x86_64 - ghc-8.10
git rev 01bda2e2cb0a70cd95067d696dbb44665f1d680a

cardano-cli conway transaction build --mainnet --witness-override 2 --tx-in da8795bba4f4549b7987aac5ae240f941d2ebb93fa15eb288987851ef73b241e#1 --withdrawal stake1uxc2mze08jpandr4552xscp4vs2spe5uqeyt8jyjq3ynydcu0l6c2+2695208894 --tx-out Ae2tdPwUPEYzuiAjQwyVoweSXt9KzX3jxw4vPpCTv3Bi7o134EdPdNsbiaW+2695208894 --change-address addr1qyc9q2juznjj52hujclkt37xt99nt9p3zcys9wwkf6mlp89s4k9j70yrmx68tfg5dpsr2eq4qrnfcpjgk0yfypzfxgms22rwuh --out-file tx.raw

cardano-cli: Illegal Value in TxOut: MaryValue (Coin (-1694702387)) (MultiAsset (fromList []))
CallStack (from HasCallStack):
  error, called at src/Cardano/Ledger/Babbage/TxOut.hs:401:25 in cardano-ledger-babbage-1.10.0.0-oRnre4HZULFAKhFSl9oK6:Cardano.Ledger.Babbage.TxOut
  mkTxOut, called at src/Cardano/Ledger/Babbage/TxOut.hs:372:44 in cardano-ledger-babbage-1.10.0.0-oRnre4HZULFAKhFSl9oK6:Cardano.Ledger.Babbage.TxOut
  BabbageTxOut, called at src/Cardano/Ledger/Conway/TxOut.hs:40:26 in cardano-ledger-conway-1.17.2.0-DjShi1w51BjCHAy5SUbvk1:Cardano.Ledger.Conway.TxOut
  mkBasicTxOut, called at internal/Cardano/Api/Tx/Body.hs:3148:13 in cardano-api-10.1.0.0-Gk2qtfoAiA71gJjiX7o8yh-internal:Cardano.Api.Tx.Body
  toShelleyTxOutAny, called at internal/Cardano/Api/Tx/Body.hs:2400:41 in cardano-api-10.1.0.0-Gk2qtfoAiA71gJjiX7o8yh-internal:Cardano.Api.Tx.Body
```

**Comment by carbolymer** [comment]
Possible duplicate of:
- https://github.com/IntersectMBO/cardano-cli/issues/904

I think the fix is on its way to get integrated to cardano-cli:
- https://github.com/IntersectMBO/cardano-api/pull/666

**Comment by vshybalov** [comment]
@carbolymer 

The only difference with the #904 issue,  is that there -1 value in the arguments. However in my case there is no negative values, so it is interesting where cli take that negative number from.

**Comment by carbolymer** [comment]
@vshybalov Ah right, good catch. Yes indeed it looks different. Most likely related to autobalancing.

**Comment by CarlosLopezDeLara** [comment]
@carbolymer Do you have a reproduction for this? I'd like to check if the issue is indeed fixed with `cardano-cli-10.2.0.0`.

**Comment by carbolymer** [comment]
@CarlosLopezDeLara No I haven't got to it yet.

**Comment by CarlosLopezDeLara** [comment]
Can't reproduce: 
```
cardano-cli --version 
cardano-cli 10.1.1.0 - linux-x86_64 - ghc-9.6
```

```
cardano-cli conway transaction build --tx-in bc4f601be2f7f86af8c6e3de92dad9cba977e622febd962144e0f20bcff6f4d7#0 --withdrawal stake_test1urcu5556u6dtrgyqfurpg78h2xprlvhekptrk8d3yxaevdq72u408+136062162 --witness-override 2 --change-address addr_test1qpcw2v0ms5npl62qncduelwj4cwsr0xn57g5rrmu3g5pw603efff4e56kxsgqncxz3u0w5vz87e0nvzk8vwmzgdmjc6q7knac6 --out-file example/transactions/tx.raw
Estimated transaction fee: 180417 Lovelace

cardano-cli conway transaction sign --tx-body-file example/transactions/tx.raw --signing-key-file example/utxo-keys/payment1.skey --signing-key-file example/utxo-keys/stake1.skey --out-file example/transactions/tx.signed

cardano-cli conway transaction submit --tx-file example/transactions/tx.signed
Transaction successfully submitted.
```

**Comment by KtorZ** [comment]
Note: the problem still exists as per `cardano-cli 10.4.0.0` (and I assume it's still also present in recent versions since I've seen no evidence of it being fixed in recent releases). 

To reproduce you need:

- Have a large withdrawal 
- To explicitly set an output amount 
- Have the set amount be larger than the total amount provided by the sum of all inputs (thus requiring the withdrawal)

I believe that the root cause comes from the balancing step which doesn't correctly include the amount coming from the withdrawal. Take for example:

```
cardano-cli conway transaction build \
  --tx-in                                      60ed6ab43c840ff888a8af30a1ed27b41e9f4a91a89822b2b63d1bfc52aeec45#0 \
  --tx-in-collateral                           60ed6ab43c840ff888a8af30a1ed27b41e9f4a91a89822b2b63d1bfc52aeec45#0 \
  --withdrawal                                 stake1790mk0jjjhppr36ethwj8kewpgyrxyc7q6qucl4gqru96dqh6k4q9+2575000000000 \
  --withdrawal-tx-in-reference                 87ee53271fb41021efa13c2dbe2998c18ead07d32a6ab6dda184853ed7e39aae#00 \
  --withdrawal-plutus-script-v3                \
  --withdrawal-reference-tx-in-redeemer-value  "[]" \
  --tx-out                                     addr1x90mk0jjjhppr36ethwj8kewpgyrxyc7q6qucl4gqru96dzlhvl999wzz8r4jhway0djuzsgxvf3up5pe3l2sq8ct56qtjz6ah+2575000000000 \
  --change-address                             addr1qxu84ftxpzh3zd8p9awp2ytwzk5exj0fxcj7paur4kd4ytun36yuhgl049rxhhuckm2lpq3rmz5dcraddyl45d6xgvqqsp504c \
  --invalid-hereafter                          185068799 \
  --mainnet                                   \
  --out-file                                   /var/folders/dt/0ljc42hs50n1gk332s0kgq3h0000gn/T/tmp.xqHTQXb15c
```

This results in:

```
cardano-cli: Illegal Value in TxOut: MaryValue (Coin (-2574925343204)) (MultiAsset (fromList []))
CallStack (from HasCallStack):
  error, called at src/Cardano/Ledger/Babbage/TxOut.hs:401:25 in crdn-ldgr-bbbg-1.10.1.0-51232b58:Cardano.Ledger.Babbage.TxOut
  mkTxOut, called at src/Cardano/Ledger/Babbage/TxOut.hs:372:44 in crdn-ldgr-bbbg-1.10.1.0-51232b58:Cardano.Ledger.Babbage.TxOut
  BabbageTxOut, called at src/Cardano/Ledger/Conway/TxOut.hs:40:26 in crdn-ldgr-cnwy-1.18.1.0-3d5dfa9c:Cardano.Ledger.Conway.TxOut
  mkBasicTxOut, called at internal/Cardano/Api/Tx/Body.hs:3410:13 in crdn-p-10.8.0.0-6d2ee359:Cardano.Api.Tx.Body
  toShelleyTxOutAny, called at internal/Cardano/Api/Tx/Body.hs:2668:41 in crdn-p-10.8.0.0-6d2ee359:Cardano.Api.Tx.Body%
```

**Comment by carbolymer** [comment]
I think this was fixed in https://github.com/IntersectMBO/cardano-api/pull/799

From my tests this is not reproducible on latest cardano-cli. I've added regression tests in: https://github.com/IntersectMBO/cardano-node/pull/6540 

There's a gap in error handling which may result in an error like that printed when the transaction does not balance. I've added more test coverage and reporting of better error message. https://github.com/IntersectMBO/cardano-api/pull/1186

@KtorZ can you let me know if you can still reproduce this on latest cardano-cli?

**Comment by carbolymer** [comment]
Closing. Let me know if the issue is still present.
